services:
  pob-format:
    build: .
    #image: ghcr.io/paliak/busted-tests:latest
    container_name: pob-format
    command: >
      find . -name '*.lua'
      ! -path "./src/TreeData/*"
      ! -path "./src/Export/*"
      ! -path "./src/Data/*"
      ! -path "./runtime/*"
      -print
      -exec lua-format -i {} \;
    security_opt:
      - no-new-privileges:true
    working_dir: /workdir
    volumes:
      - ./:/workdir
  busted-tests:
    #build: .
    image: ghcr.io/paliak/busted-tests:latest
    environment:
      HOME: /tmp
    container_name: busted-tests
    user: nobody:nobody
    command: busted --lua=luajit
    security_opt:
      - no-new-privileges:true
    ports:
      - "9966:9966"
    working_dir: /workdir
    volumes:
      - ./:/workdir:ro
  busted-diff:
    #build: .
    image: ghcr.io/paliak/busted-tests:latest
    environment: #Where in the container the folders are stored
      WORKDIR: /workdir
      HOME: /tmp
      DEVREF: ${DEVREF:-origin/dev}
      HEADREF: $HEADREF
    container_name: busted-diff
    tty: true
    user: nobody:nobody
    command: /bin/sh -c "dos2unix < /workdir/spec/BuildDiff.sh | /bin/sh"
    security_opt:
      - no-new-privileges:true
    working_dir: /workdir
    volumes:
      - ./:/workdir:ro
