services:
  busted-tests:
    #build: .
    image: ghcr.io/paliak/busted-tests
    container_name: busted-tests
    ports:
      - "9966:9966"
    volumes:
      - ./:/root
  busted-diff:
    #build: .
    image: ghcr.io/paliak/busted-tests
    container_name: busted-diff
    command: /bin/sh -c 'chmod 777 ./spec/buildDiff.sh && ./spec/buildDiff.sh'
    volumes:
      - ./:/root