name: Run Tests
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run busted tests
        run: docker-compose up busted-tests

  run_build_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v4
      - name: Fetch Dev branch
        run: git fetch --depth=1
      - name: Get Dev branch HEAD hash
        id: get-dev-ref
        run: echo "devref=$(git rev-parse origin/dev)" >> $GITHUB_OUTPUT
      - name: Create cache folder
        run: mkdir /tmp/cache/
      - name: Check if build cache exists
        uses: actions/cache@v3
        with:
          path: /tmp/cache/
          key: ${{ steps.get-dev-ref.outputs.devref }}
      - name: Make sure cache is readable by docker
        run: chmod -R 777 /tmp/cache
      - name: Run build diff
        run: CACHEDIR="/tmp/cache" docker-compose up busted-diff
      