name: Run Tests
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run busted tests
        run: docker-compose up busted-tests

  run_build_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v4
      - run: git fetch --depth=1
      - name: Create cache directory
        run: mkdir /tmp/Cache
      - name: Check if build cache exists
        id: cache-builds
        uses: actions/cache@v3
        env:
          cache-name: cached-dev-builds
        with:
          path: /tmp/Cache
          key: ${{ github.event.pull_request.base.sha }}
      - name: Run build diff
        run: CACHEDIR="/tmp/Cache" docker-compose up busted-diff
      