name: Run Tests
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    container:
    # No good way to automatically get the lowercase repo owner name here.
      image: ghcr.io/paliak/busted-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run busted tests
        run: busted --lua=luajit
  run_build_diff:
    runs-on: ubuntu-latest
    container:
    # No good way to automatically get the lowercase repo owner name here.
      image: ghcr.io/paliak/busted-tests
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v4
      - name: Generate builds in reference to current commit
        run: busted --lua=luajit -r generate
      - name: Check if build cache exists
        id: cache-builds
        uses: actions/cache@v3
        env:
          cache-name: cached-dev-builds
        with:
          path: spec/Cache
          key: ${{ github.event.pull_request.base.sha }}
      - if: ${{ steps.cache-builds.outputs.cache-hit != 'true' }}
        name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: 'dev'
      - if: ${{ steps.cache-builds.outputs.cache-hit != 'true' }}
        name: Checkout new test related files in case they changed
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .busted
            spec/*
      - if: ${{ steps.cache-builds.outputs.cache-hit != 'true' }}
        name: Generate builds in reference to dev branch
        run: BUILDCACHEPREFIX='${{ github.workspace }}/spec/Cache' busted --lua=luajit -r generate
      - name: Display differences
        run: >
          for build in spec/Cache/*.lua;
          do
          BASENAME=$(basename "$build");
          echo "[-] Diff for $BASENAME";
          diff "$build" "/tmp/$BASENAME";
          echo "[+] Diff for $BASENAME";
          done
