name: Run Tests
on:
  workflow_dispatch:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    container:
    # No good way to automatically get the lowercase repo owner name here.
      image: ghcr.io/paliak/busted-tests:latest
      volumes:
        - ${{ github.workspace }}:/root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run busted tests
        run: busted --lua=luajit